name: Continuous Deployment

on:
  push:
    branches:
      - feature/deploy

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" > deploy/.env

      - name: Build & deploy image
        run: |
          make build-app
          make deploy-app