name: Continuous Integration

on:
  push:
    branches:
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" > deploy/.env

      - name: Run a test
        run: |
          make test-app
